package com.example.domain.model.contact

data class ContactSyncRecord(
    val id: String,
    val googleContactId: String? = null,
    val displayName: String,
    val nickname: String? = null,
    val primaryPhone: String? = null,
    val secondaryPhone: String? = null,
    val primaryEmail: String? = null,
    val company: String? = null,
    val jobTitle: String? = null,
    val address: String? = null,
    val profilePhotoUri: String? = null,
    val contactGroup: String? = null,
    val relationshipType: String = "UNKNOWN",
    val birthdayDay: Int? = null,
    val birthdayMonth: Int? = null,
    val birthdayYear: Int? = null,
    val anniversaryDay: Int? = null,
    val anniversaryMonth: Int? = null,
    val anniversaryYear: Int? = null,
    val workStartDay: Int? = null,
    val workStartMonth: Int? = null,
    val workStartYear: Int? = null,
    val relationsJson: String = "[]",
    val notesText: String = "",
    val isDeleted: Boolean = false,
)
