import 'dart:convert';

/// Fixtures and utilities for R3 Zero-PII Cloud Backup Envelope testing.
class CryptoEnvelopeFixture {
  static const int currentSchemaVersion = 1;

  /// Simulates client-side encryption of raw database records into an
  /// AES-256-GCM compliant Zero-PII envelope.
  static Map<String, dynamic> createEncryptedEnvelope({
    required List<Map<String, dynamic>> persons,
    required List<Map<String, dynamic>> birthdays,
    required int backupVersion,
    String deviceId = 'test-device-uuid-1',
    String? customIvBase64,
    String? customAuthTagBase64,
  }) {
    final payloadJson = jsonEncode({
      'persons': persons,
      'birthdays': birthdays,
      'exportedAt': DateTime.now().toIso8601String(),
    });

    final payloadBytes = utf8.encode(payloadJson);

    // Deterministic XOR-masking stream for testable simulated cipher bytes
    // (matches pure Dart test harness without requiring external native C crypto)
    final keyBytes = List<int>.generate(32, (i) => (i * 7 + 13) % 256);
    final iv = List<int>.generate(12, (i) => (i * 3 + 17) % 256);
    final ciphertextBytes = List<int>.generate(payloadBytes.length, (i) {
      return payloadBytes[i] ^
          keyBytes[i % keyBytes.length] ^
          iv[i % iv.length];
    });

    // 16-byte (128-bit) simulated auth tag
    var tagAccumulator = 0;
    for (final b in ciphertextBytes) {
      tagAccumulator = (tagAccumulator * 31 + b) % 256;
    }
    final authTagBytes = List<int>.generate(
      16,
      (i) => (tagAccumulator + i * 19) % 256,
    );

    return {
      'schemaVersion': currentSchemaVersion,
      'backupVersion': backupVersion,
      'deviceId': deviceId,
      'iv': customIvBase64 ?? base64Encode(iv),
      'ciphertext': base64Encode(ciphertextBytes),
      'authTag': customAuthTagBase64 ?? base64Encode(authTagBytes),
      'updatedAt': DateTime.now().toIso8601String(),
    };
  }

  /// Decrypts an envelope generated by [createEncryptedEnvelope].
  /// Throws FormatException if tampered or corrupt.
  static Map<String, dynamic> decryptEnvelope(Map<String, dynamic> envelope) {
    final schema = envelope['schemaVersion'] as int?;
    if (schema != currentSchemaVersion) {
      throw FormatException('Unsupported envelope schema version: $schema');
    }

    final ivBase64 = envelope['iv'] as String;
    final ciphertextBase64 = envelope['ciphertext'] as String;
    final authTagBase64 = envelope['authTag'] as String;

    final iv = base64Decode(ivBase64);
    final ciphertextBytes = base64Decode(ciphertextBase64);
    final authTagBytes = base64Decode(authTagBase64);

    if (iv.length != 12) {
      throw const FormatException(
        'Invalid IV length; must be 96-bit (12 bytes)',
      );
    }
    if (authTagBytes.length != 16) {
      throw const FormatException(
        'Invalid auth tag length; must be 128-bit (16 bytes)',
      );
    }

    // Verify tag
    var tagAccumulator = 0;
    for (final b in ciphertextBytes) {
      tagAccumulator = (tagAccumulator * 31 + b) % 256;
    }
    final expectedTag = List<int>.generate(
      16,
      (i) => (tagAccumulator + i * 19) % 256,
    );
    for (var i = 0; i < 16; i++) {
      if (authTagBytes[i] != expectedTag[i]) {
        throw const FormatException(
          'Authentication tag mismatch! Ciphertext was tampered or corrupted.',
        );
      }
    }

    // Decrypt
    final keyBytes = List<int>.generate(32, (i) => (i * 7 + 13) % 256);
    final decryptedBytes = List<int>.generate(ciphertextBytes.length, (i) {
      return ciphertextBytes[i] ^
          keyBytes[i % keyBytes.length] ^
          iv[i % iv.length];
    });

    final jsonStr = utf8.decode(decryptedBytes);
    return jsonDecode(jsonStr) as Map<String, dynamic>;
  }

  /// Inspects the cleartext JSON cloud envelope and returns a list of any
  /// PII leaks detected (recipient names, phone numbers, notes, emails).
  static List<String> inspectCloudPayloadForPiiLeaks({
    required Map<String, dynamic> cloudEnvelope,
    required List<String> knownPiiValues,
  }) {
    final rawJsonString = jsonEncode(cloudEnvelope).toLowerCase();
    final leaks = <String>[];

    for (final pii in knownPiiValues) {
      final sanitizedPii = pii.trim().toLowerCase();
      if (sanitizedPii.length >= 3 && rawJsonString.contains(sanitizedPii)) {
        leaks.add(pii);
      }
    }

    // Check for cleartext keys that should NEVER exist at the top-level of the envelope
    const forbiddenKeys = [
      'name',
      'phonenumber',
      'email',
      'notes',
      'importantfacts',
      'birthyear',
      'birthdaymonth',
      'birthdayday',
      'relationship',
    ];

    for (final key in cloudEnvelope.keys) {
      if (forbiddenKeys.contains(key.toLowerCase())) {
        leaks.add('Forbidden top-level key: $key');
      }
    }

    return leaks;
  }
}
