import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:ai_birthday/core/errors/app_failure.dart';
import 'package:ai_birthday/core/security/credential_storage.dart';
import 'package:ai_birthday/features/ai/domain/ai_prompt_builder.dart';
import 'package:ai_birthday/features/ai/domain/ai_provider.dart';
import 'package:ai_birthday/features/ai/domain/ai_router.dart';
import 'package:ai_birthday/features/people/domain/models/person.dart';
import 'package:ai_birthday/features/subscription/domain/entitlement.dart';

class MockAiProvider implements AiMessageProvider {
  MockAiProvider(this.providerId, this.responseMessage);

  @override
  final String providerId;
  final String responseMessage;

  @override
  Future<AiGenerationResult> generateMessage(
    AiGenerationRequest request,
  ) async {
    return AiGenerationResult(
      message: responseMessage,
      providerType: providerId,
    );
  }
}

/// Provider that never completes — used to prove the router's timeout bound.
class HangingAiProvider implements AiMessageProvider {
  @override
  final String providerId = 'hanging';

  @override
  Future<AiGenerationResult> generateMessage(AiGenerationRequest request) {
    return Completer<AiGenerationResult>().future;
  }
}

void main() {
  group('AiRouter Routing Rules (SSOT §5)', () {
    late InMemoryCredentialStorage credentialStorage;
    late MockAiProvider mockGeminiProvider;
    late MockAiProvider mockNanoProvider;
    late Person testPerson;

    setUp(() {
      credentialStorage = InMemoryCredentialStorage();
      mockGeminiProvider = MockAiProvider(
        'user_gemini',
        'Generated by Cloud Gemini',
      );
      mockNanoProvider = MockAiProvider(
        'gemini_nano',
        'Generated by Gemini Nano',
      );
      testPerson = Person(
        id: 'p-1',
        name: 'Diana',
        birthdayMonth: 7,
        birthdayDay: 20,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
    });

    test('Throws AppFailure.lockedAi when entitlement is not active', () async {
      final router = AiRouter(
        credentialStorage: credentialStorage,
        userGeminiProvider: mockGeminiProvider,
        nanoProvider: mockNanoProvider,
      );

      expect(
        () => router.generate(
          request: AiGenerationRequest(person: testPerson),
          entitlement: UserEntitlement.free,
        ),
        throwsA(
          isA<AppFailure>().having(
            (e) => e.code,
            'code',
            AppFailureCode.aiLocked,
          ),
        ),
      );
    });

    test(
      'Routes to UserGeminiApiProvider when user key is configured',
      () async {
        await credentialStorage.saveGeminiApiKey('AIzaSyDummyKey');

        final router = AiRouter(
          credentialStorage: credentialStorage,
          userGeminiProvider: mockGeminiProvider,
          nanoProvider: mockNanoProvider,
        );

        final result = await router.generate(
          request: AiGenerationRequest(person: testPerson),
          entitlement: UserEntitlement.proActive,
        );

        expect(result.providerType, 'user_gemini');
        expect(result.message, 'Generated by Cloud Gemini');
      },
    );

    test(
      'Routes to GeminiNanoProvider when no user key is configured but Nano is available',
      () async {
        final router = AiRouter(
          credentialStorage: credentialStorage,
          userGeminiProvider: mockGeminiProvider,
          nanoProvider: mockNanoProvider,
          nanoStatusChecker: () async => GeminiNanoStatus.available,
        );

        final result = await router.generate(
          request: AiGenerationRequest(person: testPerson),
          entitlement: UserEntitlement.proActive,
        );

        expect(result.providerType, 'gemini_nano');
        expect(result.message, 'Generated by Gemini Nano');
      },
    );

    test(
      'Throws AppFailure.credentialMissing when no key and Nano is unavailable',
      () async {
        final router = AiRouter(
          credentialStorage: credentialStorage,
          userGeminiProvider: mockGeminiProvider,
          nanoProvider: mockNanoProvider,
          nanoStatusChecker: () async => GeminiNanoStatus.unavailable,
        );

        expect(
          () => router.generate(
            request: AiGenerationRequest(person: testPerson),
            entitlement: UserEntitlement.proActive,
          ),
          throwsA(
            isA<AppFailure>().having(
              (e) => e.code,
              'code',
              AppFailureCode.aiCredentialMissing,
            ),
          ),
        );
      },
    );

    test(
      'a stalled provider maps to a retryable aiTimeout instead of hanging',
      () async {
        await credentialStorage.saveGeminiApiKey('AIzaSyDummyKey');

        final router = AiRouter(
          credentialStorage: credentialStorage,
          userGeminiProvider: HangingAiProvider(),
          generationTimeout: const Duration(milliseconds: 50),
        );

        expect(
          () => router.generate(
            request: AiGenerationRequest(person: testPerson),
            entitlement: UserEntitlement.proActive,
          ),
          throwsA(
            isA<AppFailure>().having(
              (e) => e.code,
              'code',
              AppFailureCode.aiTimeout,
            ),
          ),
        );
      },
    );
  });
}
