package com.example.ui

import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class LocalizationParityTest {

    @Test
    fun appStrings_haveHindiParity() {
        assertStringKeyParity(
            englishPath = "app/src/main/res/values/strings.xml",
            hindiPath = "app/src/main/res/values-hi/strings.xml",
        )
    }

    @Test
    fun coreDataStrings_haveHindiParity() {
        assertStringKeyParity(
            englishPath = "core/data/src/main/res/values/strings.xml",
            hindiPath = "core/data/src/main/res/values-hi/strings.xml",
        )
    }

    @Test
    fun appHindiPrimaryWorkflowStrings_haveReviewedHindiCopy() {
        val hindiValues = stringValues(sourceFile("app/src/main/res/values-hi/strings.xml"))

        val failures = REVIEWED_APP_HINDI_KEYS.mapNotNull { key ->
            val value = hindiValues[key] ?: return@mapNotNull "$key is missing"
            val stalePhrase = STALE_PRIMARY_WORKFLOW_ENGLISH_PHRASES.firstOrNull { phrase ->
                value.contains(phrase, ignoreCase = true)
            }

            when {
                !value.containsDevanagari() -> "$key has no Devanagari text: $value"
                stalePhrase != null -> "$key still contains stale English phrase \"$stalePhrase\": $value"
                else -> null
            }
        }

        assertTrue(
            "Reviewed primary Hindi workflow strings should not regress to stale English copy:\n" +
                failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    private fun assertStringKeyParity(englishPath: String, hindiPath: String) {
        val englishKeys = stringKeys(sourceFile(englishPath))
        val hindiKeys = stringKeys(sourceFile(hindiPath))

        assertEquals(
            "Hindi string resources must contain the same keys as English resources for $englishPath",
            englishKeys,
            hindiKeys,
        )
    }

    private fun stringKeys(file: File): Set<String> {
        return stringValues(file).keys
    }

    private fun stringValues(file: File): Map<String, String> {
        val document = DocumentBuilderFactory.newInstance()
            .newDocumentBuilder()
            .parse(file)
        val nodes = document.getElementsByTagName("string")
        return buildMap {
            for (index in 0 until nodes.length) {
                val node = nodes.item(index)
                put(
                    node.attributes.getNamedItem("name").nodeValue,
                    node.textContent,
                )
            }
        }
    }

    private fun String.containsDevanagari(): Boolean {
        return any { character -> character.code in DEVANAGARI_RANGE }
    }

    private fun sourceFile(rootRelativePath: String): File {
        return listOf(
            File(rootRelativePath),
            File("../$rootRelativePath"),
        ).firstOrNull { it.exists() }
            ?: error("Could not locate source file $rootRelativePath from ${File(".").absolutePath}")
    }

    private companion object {
        val DEVANAGARI_RANGE = 0x0900..0x097F

        val REVIEWED_APP_HINDI_KEYS = listOf(
            "widget_birthday_description",
            "shortcut_compose",
            "shortcut_compose_long",
            "shortcut_contacts",
            "shortcut_contacts_long",
            "accessibility_service_description",
            "onboarding_welcome_title",
            "onboarding_welcome_subtitle",
            "onboarding_step_text",
            "onboarding_skip",
            "memory_vault_suggested_prompts_title",
            "memory_prompt_favorite_food",
            "memory_prompt_recent_life_update",
            "memory_prompt_inside_joke",
            "memory_prompt_things_to_avoid",
            "memory_prompt_gift_preference",
            "contact_health_score",
            "contact_engagement_score",
            "contact_points",
            "contact_communication_style",
            "contact_automation_settings",
            "contact_dnd_label",
            "contact_dnd_subtitle",
            "contact_send_time_label",
            "contact_send_time_default",
            "contact_detail_chat_history",
            "contact_detail_contact_info",
            "contact_detail_unknown",
            "contact_detail_birthday_format",
            "contact_detail_next_birthday",
            "contact_detail_no_upcoming_event",
            "contact_detail_generate_ai_wish",
            "contact_detail_section_personalization",
            "contact_detail_section_automation",
            "contact_detail_section_history",
            "contact_detail_error_no_upcoming_event",
            "contact_detail_error_already_generated",
            "contact_detail_error_event_not_found",
            "contact_detail_error_contact_not_found",
            "messages_no_recent",
            "chat_history_title",
            "chat_history_subtitle",
            "chat_history_empty",
            "chat_history_error_load",
            "chat_history_sent_via_format",
            "wish_preview_title",
            "wish_preview_test_sent",
            "wish_preview_choose_tone",
            "wish_preview_message_label",
            "wish_preview_regenerate",
            "wish_preview_reject",
            "wish_preview_approve_schedule",
            "wish_preview_approved",
            "wish_preview_rejected",
            "wish_preview_review_next",
            "wish_preview_review_next_count_one",
            "wish_preview_review_next_count_many",
            "wish_variant_short",
            "wish_variant_standard",
            "wish_variant_long",
            "wish_variant_formal",
            "wish_variant_funny",
            "wish_variant_emotional",
            "wish_feedback_too_generic",
            "wish_feedback_too_formal",
            "wish_feedback_wrong_language",
            "wish_feedback_too_long",
            "wish_feedback_not_warm",
            "wish_feedback_repetitive",
            "wish_preview_feedback_saved",
            "wish_preview_quality_template_used",
            "wish_preview_quality_regenerated",
            "wish_preview_quality_regenerated_with_feedback",
            "wish_preview_quality_next_regeneration",
            "wish_preview_send_summary_title",
            "wish_preview_summary_event",
            "wish_preview_summary_route",
            "wish_preview_summary_schedule",
            "wish_preview_summary_approval",
            "wish_preview_summary_quality",
            "wish_preview_summary_quality_ai",
            "wish_preview_summary_quality_fallback",
            "wish_preview_readiness_ready",
            "wish_preview_readiness_edited",
            "wish_preview_readiness_short",
            "wish_preview_readiness_blank",
            "wish_preview_error_unknown",
            "analytics_reconnect",
            "analytics_relationship_insights",
            "analytics_thriving_health",
            "analytics_fading_health",
            "events_send_message",
            "events_generate_wish",
            "events_no_upcoming_reminders",
            "events_contact_label",
            "events_day_label",
            "events_month_label",
            "events_year_label",
            "events_birthdays_this_month",
            "dashboard_start_syncing",
            "dashboard_no_upcoming_reminders",
            "onboarding_write_sample_a",
            "onboarding_write_sample_b",
            "settings_configuration",
            "settings_gemini_api_key",
            "settings_sender_email",
            "settings_app_password",
            "settings_quiet_hrs_start",
            "settings_quiet_hrs_end",
            "settings_backup_encryption_passphrase",
            "settings_restore_encryption_passphrase",
            "settings_passphrase",
            "settings_paste_samples",
            "automation_setup_title",
            "automation_setup_subtitle",
            "automation_setup_diagnostic_checks",
            "automation_setup_recommended_fix",
            "automation_setup_action_refresh",
            "automation_setup_action_dry_run",
            "automation_setup_action_sync_contacts",
            "automation_setup_action_test_ai",
            "automation_setup_action_open_settings",
            "automation_setup_action_review_contacts",
            "automation_setup_action_open_accessibility",
            "automation_setup_action_open_battery_settings",
            "automation_setup_action_app_settings",
            "automation_setup_action_view_activity",
            "automation_setup_action_done",
            "automation_setup_sync_success",
            "automation_setup_sync_failed",
            "automation_setup_dry_run_blocker",
            "automation_setup_dry_run_ready",
            "automation_setup_dry_run_missing_ai",
            "automation_setup_ai_test_failed",
            "automation_setup_check_google_contacts",
            "automation_setup_google_contacts_ok",
            "automation_setup_google_contacts_missing",
            "automation_setup_gemini_key_ok",
            "automation_setup_gemini_auth_missing",
            "automation_setup_check_ai_wish_generation",
            "automation_setup_ai_wish_enabled",
            "automation_setup_ai_wish_disabled",
            "dashboard_contacts",
            "dashboard_upcoming_events",
            "dashboard_pending_messages",
            "dashboard_quick_actions",
            "dashboard_sync_contacts",
            "dashboard_generate_wishes",
            "dashboard_backup_data",
            "dashboard_pending_approvals",
            "events_filter_all",
            "events_filter_birthdays",
            "events_filter_anniversaries",
            "events_filter_work",
            "events_filter_custom",
            "events_review_send",
            "messages_pending",
            "messages_sent_history",
            "messages_approve_send",
            "messages_edit",
            "messages_reject",
            "analytics_overall_health",
            "analytics_messages_sent",
            "analytics_events_covered",
            "analytics_avg_response",
            "events_error_load",
            "events_error_refresh",
            "events_error_resolution",
            "events_error_selected_contact_not_found",
            "events_error_event_not_found",
            "events_error_missing_contact",
            "events_error_invalid_date",
            "events_saved_message",
            "events_saved_activity_title",
            "events_saved_activity_detail",
            "events_duplicate_title",
            "events_duplicate_message",
            "events_duplicate_save_anyway",
            "events_conflict_title",
            "events_conflict_message",
            "event_source_contacts",
            "event_source_manual",
            "event_source_calendar",
            "event_source_ai_inferred",
            "event_source_merged",
            "event_source_conflict",
            "event_source_unknown",
            "event_verification_verified",
            "event_verification_needs_review",
            "event_verification_conflict",
            "event_conflict_duplicate",
            "event_conflict_date",
            "event_resolution_merge_here",
            "event_resolution_merged_message",
            "event_resolution_keep_separate_message",
            "event_resolution_no_conflict_message",
            "event_resolution_merged_activity_title",
            "event_resolution_keep_separate_activity_title",
            "event_resolution_activity_detail",
            "messages_tab_needs_review",
            "messages_tab_scheduled",
            "messages_tab_blocked",
            "messages_deleted_contact",
            "messages_error_load",
            "messages_error_approve",
            "messages_error_reject",
            "messages_error_retry",
            "messages_error_revoke",
            "messages_error_bulk_approve",
            "messages_error_bulk_reject",
            "messages_error_bulk_retry",
            "message_activity_approved_title",
            "message_activity_approved_detail",
            "message_activity_rejected_title",
            "message_activity_rejected_detail",
            "message_activity_retried_title",
            "message_activity_retried_detail",
            "message_activity_bulk_approved_title",
            "message_activity_bulk_approved_detail",
            "message_activity_bulk_rejected_title",
            "message_activity_bulk_rejected_detail",
            "message_activity_bulk_retried_title",
            "message_activity_bulk_retried_detail",
            "message_activity_approval_revoked_title",
            "message_activity_approval_revoked_detail",
            "wish_why_title",
            "wish_why_relationship",
            "wish_why_language",
            "wish_why_channel",
            "wish_why_tone",
            "wish_why_memories",
            "wish_why_gifts",
            "wish_why_previous",
            "widget_birthdays_today",
            "widget_unknown_contact",
            "widget_next_events",
            "widget_pending_approvals",
            "widget_enjoy_day",
            "onboarding_setup_subtitle",
            "onboarding_setup_google_title",
            "onboarding_setup_google_description",
            "onboarding_setup_contacts_title",
            "onboarding_setup_contacts_description",
            "onboarding_setup_ai_title",
            "onboarding_setup_ai_description",
            "onboarding_setup_permissions_title",
            "onboarding_setup_permissions_description",
            "onboarding_setup_style_title",
            "onboarding_setup_automation_title",
            "onboarding_setup_automation_description",
            "contact_detail_error_ai_disabled",
            "wish_preview_error_message_not_found",
            "wish_preview_error_load",
            "wish_preview_error_ai_disabled",
            "wish_preview_error_context_not_found",
            "onboarding_sample_a_placeholder",
            "onboarding_sample_b_placeholder",
            "settings_samples_placeholder",
            "style_coach_samples_placeholder",
            "automation_setup_ai_test_success",
            "automation_setup_style_trained",
            "automation_setup_style_needs_more",
            "automation_setup_style_empty",
            "automation_setup_check_personalization",
            "automation_setup_personalization_empty",
            "automation_setup_personalization_ok",
            "automation_setup_personalization_low",
            "automation_setup_check_generic_messages",
            "automation_setup_generic_messages_empty",
            "automation_setup_generic_messages_ok",
            "automation_setup_generic_messages_low",
            "automation_setup_check_gemini_circuit",
            "automation_setup_gemini_circuit_ok",
            "automation_setup_gemini_circuit_state",
            "automation_setup_gemini_circuit_none",
            "automation_setup_check_notifications",
            "automation_setup_notifications_ok",
            "automation_setup_notifications_missing",
            "automation_setup_sms_ok",
            "automation_setup_sms_missing",
            "automation_setup_check_whatsapp",
            "automation_setup_whatsapp_ok",
            "automation_setup_whatsapp_missing",
            "automation_setup_check_exact_sends",
            "automation_setup_exact_sends_ok",
            "automation_setup_exact_sends_missing",
            "automation_setup_check_daily_automation",
            "automation_setup_daily_ok",
            "automation_setup_daily_missing",
            "automation_setup_check_recent_errors",
            "automation_setup_recent_errors_none",
            "automation_setup_check_dead_letter",
            "automation_setup_dead_letter_none",
            "automation_setup_dead_letter_count",
            "automation_setup_dead_letter_count_with_memory",
            "automation_setup_dead_letter_latest",
            "automation_setup_summary_blockers",
            "automation_setup_summary_required",
            "automation_setup_summary_warnings",
            "automation_setup_summary_review_warnings",
            "automation_setup_summary_ok",
            "automation_setup_summary_ok_detail",
            "automation_setup_ai_error_quota",
            "automation_setup_ai_error_auth",
            "automation_setup_ai_error_network",
            "automation_setup_ai_error_json",
            "automation_setup_ai_error_circuit",
            "automation_setup_ai_error_recent",
            "automation_setup_whatsapp_card_title",
            "automation_setup_whatsapp_consent_label",
            "automation_setup_whatsapp_consent_needed",
            "automation_setup_whatsapp_consent_saved",
            "automation_setup_battery_card_title",
            "automation_setup_battery_card_ignored",
            "automation_setup_battery_card_body",
            "automation_setup_notifications_card_title",
            "automation_setup_notifications_card_body",
            "automation_setup_approval_card_title",
            "automation_setup_approval_card_body",
            "edit_contact_title",
            "edit_contact_full_name",
            "edit_contact_relationship",
            "edit_contact_job_title",
            "edit_contact_communication_style",
            "contacts_search_placeholder",
            "contacts_no_contacts_found",
            "notification_content_text",
            "notification_big_text",
            "message_edit_content_label",
            "auth_error_firebase",
            "auth_subtitle",
            "auth_dev_bypass",
            "auth_legal_agreement",
            "settings_sign_out_body",
            "settings_sign_out_check_local_data",
            "settings_sign_out_check_preferences",
            "settings_sign_out_check_external",
            "settings_sign_out_check_backup",
            "settings_sign_out_cancel",
            "settings_sign_out_confirm",
            "analytics_relationship_breakdown",
            "analytics_revival_suggestions",
            "settings_ai_automation",
            "settings_notifications",
            "settings_privacy_security",
            "settings_about",
            "settings_default_send_time",
            "settings_analytics_subtitle",
            "settings_automation_setup",
            "settings_automation_setup_subtitle",
            "settings_gemini_api_key_help",
            "settings_save_api_key",
            "settings_email_sending_title",
            "settings_email_sending_help",
            "settings_save_email_settings",
            "settings_email_saved",
            "settings_email_setup_required",
            "settings_quiet_hours_title",
            "settings_quiet_hours_help",
            "settings_save_quiet_hours",
            "settings_quiet_hours_saved",
            "settings_quiet_hours_invalid",
            "backup_actions_section",
            "backup_import_replace_warning",
            "backup_action_failed_title",
            "setup_progress_title",
            "setup_progress_count",
            "setup_progress_blockers",
            "setup_progress_warnings",
            "setup_progress_ready",
            "home_default_user",
            "home_next_action_section",
            "home_next_action_sync_contacts_title",
            "home_next_action_sync_contacts_detail",
            "home_next_action_fix_contact_sync_title",
            "home_next_action_fix_contact_sync_detail",
            "home_next_action_connect_ai_title",
            "home_next_action_connect_ai_detail",
            "home_next_action_enable_ai_title",
            "home_next_action_enable_ai_detail",
            "home_next_action_review_pending_title",
            "home_next_action_review_pending_detail",
            "home_next_action_reconnect_title",
            "home_next_action_reconnect_detail",
            "home_backup_never_title",
            "home_backup_never_detail",
            "home_backup_stale_title",
            "home_backup_stale_detail",
            "home_readiness_setup_attention_title",
            "home_readiness_approvals_waiting_title",
            "home_planner_reconnect_detail",
            "home_planner_upcoming_detail",
            "relationship_planner_title",
            "contact_detail_edit_preferences",
            "contact_detail_quick_enrichment",
            "contact_detail_personalization_actions",
            "contact_detail_automation_actions",
            "contact_detail_add_memory",
            "contact_detail_add_gift",
            "contact_detail_mark_vip",
            "contact_detail_preferences_saved",
            "contact_detail_preferences_contact_not_found",
            "contact_preferences_error_relationship_required",
            "contact_preferences_error_language_required",
            "contact_preferences_error_channel_unsupported",
            "contact_preferences_error_automation_mode_unsupported",
            "contact_preferences_error_send_hour",
            "contact_preferences_error_send_minute",
            "contact_preferences_error_send_time_incomplete",
            "contact_preferences_error_negative_budget",
            "contact_preferences_title",
            "contact_preferences_nickname",
            "contact_preferences_relationship_type",
            "contact_preferences_language",
            "contact_preferences_channel",
            "contact_preferences_formality",
            "contact_preferences_style",
            "contact_preferences_automation_mode",
            "contact_preferences_send_time",
            "contact_preferences_gift_budget",
            "contact_preferences_annual_budget",
            "contact_preferences_interests",
            "contact_preferences_sensitive_topics",
            "contact_preferences_life_phase",
            "contact_preferences_notes",
            "contact_preferences_skip_auto_wish",
            "language_english",
            "language_hindi",
            "formality_casual",
            "formality_semi_formal",
            "formality_formal",
            "style_warm",
            "style_funny",
            "style_professional",
            "style_emotional",
            "automation_mode_default",
            "automation_mode_fully_auto",
            "automation_mode_smart_approve_default",
            "automation_mode_vip_approve",
            "automation_mode_always_ask",
            "contact_preferences_invalid_send_time",
            "personalization_quality_title",
            "personalization_quality_nickname",
            "personalization_quality_interests",
            "personalization_quality_memory_notes",
            "personalization_quality_channel",
            "personalization_quality_next_step",
            "personalization_quality_ready",
            "personalization_quality_impact_low",
            "personalization_quality_impact_partial",
            "personalization_quality_impact_ready",
            "personalization_quality_memory_summary",
            "personalization_quality_add_one_memory",
            "personalization_quality_add_nickname",
            "personalization_quality_add_interests",
            "personalization_quality_add_memory_notes",
            "personalization_quality_choose_channel",
            "contact_filter_low_health",
            "contact_sort_health_high",
            "contact_sort_health_low",
            "contact_list_sync_failed",
            "messages_empty_needs_review",
            "messages_empty_scheduled",
            "messages_empty_blocked",
            "messages_recovery_title",
            "messages_recovery_summary",
            "messages_recovery_setup_detail",
            "messages_recovery_retry_detail",
            "messages_recovery_retry_hint",
            "messages_recovery_open_setup",
            "messages_readiness_email_setup_missing",
            "messages_readiness_failed_check_setup",
            "analytics_growth_metrics",
            "analytics_delivery_reliability",
            "analytics_response_rate",
            "analytics_personalization_coverage",
            "analytics_no_neglected_contacts",
            "wish_preview_send_test",
            "channel_email",
            "automation_setup_email_missing_for_contacts",
        )

        val STALE_PRIMARY_WORKFLOW_ENGLISH_PHRASES = listOf(
            "Shows today's",
            "Compose",
            "View your contacts",
            "Never lose contact",
            "Step ",
            "Skip",
            "Memory prompts",
            "Favorite food",
            "Recent life update",
            "Inside joke",
            "Things to avoid",
            "Gift preference",
            "Health Score",
            "Engagement Score",
            "points",
            "Communication Style",
            "Automation Settings",
            "Do Not Disturb",
            "Never auto-send",
            "Custom Send Time",
            "Chat History",
            "Contact Info",
            "Unknown",
            "Birthday:",
            "Next Birthday",
            "Next Event",
            "upcoming event",
            "generated",
            "No recent messages",
            "messages sent",
            "AI Wish Preview",
            "Test message",
            "device",
            "sent",
            "Tone",
            "Message",
            "draft regenerate",
            "Reject",
            "Approve &",
            "scheduled",
            "Next review",
            "pending wish",
            "Short",
            "Standard",
            "Formal",
            "Funny",
            "Emotional",
            "Too generic",
            "Too formal",
            "Wrong language",
            "Too long",
            "Not warm enough",
            "Repeated idea",
            "Approval plan",
            "Draft quality",
            "Template fallback",
            "Unknown error",
            "Reconnect",
            "Relationship Insights",
            "Thriving",
            "Fading",
            "Send Message",
            "Generate Wish",
            "No upcoming reminders",
            "Birthdays This Month",
            "Start by syncing",
            "Write Sample Text",
            "Configuration",
            "Gemini API Key",
            "Sender Email",
            "App Password",
            "Quiet Hrs",
            "Backup Encryption Passphrase",
            "Restore Encryption Passphrase",
            "Passphrase",
            "Paste message",
            "AI Doctor",
            "Diagnostic Checks",
            "Refresh",
            "Dry Run",
            "Sync Contacts",
            "Test AI",
            "Open Settings",
            "Review Contacts",
            "Open Accessibility",
            "Open Battery Settings",
            "App Settings",
            "View Activity",
            "Done",
            "Contact sync failed",
            "Dashboard",
            "Upcoming Events",
            "Pending Messages",
            "Quick Actions",
            "Generate Wishes",
            "Backup Data",
            "Pending Approvals",
            "Birthdays",
            "Anniversaries",
            "Review & Send",
            "Pending",
            "Sent History",
            "Overall Health",
            "Events Covered",
            "Avg Response",
            "Events load",
            "Events refresh",
            "Valid date",
            "Event saved",
            "Possible duplicate",
            "Date conflict",
            "Imported",
            "Manual",
            "Calendar",
            "AI inferred",
            "Merged",
            "Verified",
            "Needs review",
            "Conflict to resolve",
            "Duplicate reminder",
            "Conflicting date",
            "Events kept separate",
            "Blocked",
            "Deleted Contact",
            "Message approved",
            "Messages approved",
            "Approval revoked",
            "Previous wishes",
            "Unknown Contact",
            "Enjoy your day",
            "Reliable imports",
            "sign in",
            "Contacts import",
            "Notifications",
            "AI wish generation",
            "Message not found",
            "Message load",
            "writing samples",
            "Writing samples",
            "Personalization Data",
            "Generic message risk",
            "Gemini Circuit",
            "WhatsApp Automation",
            "Exact Sends",
            "Daily Automation",
            "Recent Errors",
            "Dead Letter Queue",
            "AI works",
            "required setup",
            "Better results",
            "Repeated failures",
            "Edit Contact",
            "Full Name",
            "Job Title",
            "Search your contacts",
            "No contacts found",
            "Suggested message",
            "Message Content",
            "AI-powered",
            "Terms",
            "Privacy Policy",
            "Relationship Breakdown",
            "Revival Suggestions",
            "Default Send Time",
            "Restore mode",
            "Setup progress",
            "Next best action",
            "Pending wishes",
            "Relationship Planner",
            "Personalization edit",
            "Quick personalization",
            "Automation shortcuts",
            "Personalization Control",
            "Nickname",
            "Preferred language",
            "Preferred channel",
            "Custom send time",
            "Gift budget",
            "Interests",
            "Current life phase",
            "Personal notes",
            "Personalization quality",
            "Preferred channel selected",
            "memory note",
            "Failed send recovery",
            "Growth Metrics",
            "Delivery reliability",
            "Response rate",
            "Personalization coverage",
            "neglected contact",
            "Quiet hours",
        )
    }
}
